### ISSUE TITLE
[Bug]: Logo images are too big after using svg file

### ISSUE THREAD

**Issue by fu050409** [swpu-acm/algohub#136]
Consider add margin for all components using logo svg.

**Comment by fu050409** [comment]
@sunyuxi4 Hi there, would you think if it is a good way to mark paddings inside svg images to solve this issue?

**Comment by sunyuxi4** [comment]
fix(logo): Re-export svg logos. Now they looks smaller. #142

**Comment by sunyuxi4** [comment]
I've export and update new svgs. They look smaller than before now.

**Comment by sunyuxi4** [comment]
Solved.
