### ISSUE TITLE
[Docs]: Add AGPLv3 LICENSE

### ISSUE THREAD

**Issue by fu050409** [swpu-acm/algohub#140]
See title

**Comment by AndreVale69** [comment]
@fu050409 Hi, I would like to work on this issue. I will create the LICENSE file (can we find it [here](https://choosealicense.com/licenses/agpl-3.0/)) and also I will:
- Add the license notices to the program (at the beginning of each source file as a comment). The modified files will be in [src](https://github.com/swpu-acm/algohub/tree/main/src) and [src-tauri](https://github.com/swpu-acm/algohub/tree/main/src-tauri);
- Add the license notices:
    - GitHub repository link
    - Contact information (email if you want, or GitHub issue eventually)

**Comment by fu050409** [comment]
@AndreVale69 Thanks, contributions are very welcome!

**Comment by AndreVale69** [comment]
> @AndreVale69 Thanks, contributions are very welcome!

Nice! I'm going to fork the repository and start working in it.

**Comment by fu050409** [comment]
@AndreVale69 Yes, for sure :-D

**Comment by fu050409** [comment]
Resolved in #141
